In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('oe_clean.csv')
df

,gameid,league,playoffs,game,participantid,side,position,playername,gamelength,result,...,wardsplaced,wardskilled,controlwardsbought,visionscore,totalgold,earned gpm,earnedgoldshare,total cs,minionkills,monsterkills
0,TRLH3/33,EU LCS,0,1.0,3,Blue,mid,xPeke,1924,1,...,12.0,3.0,0.0,0.0,14564.0,330.6861,0.267565,276.0,247.0,29.0
1,TRLH3/33,EU LCS,0,1.0,1,Blue,top,sOAZ,1924,1,...,13.0,0.0,0.0,0.0,11499.0,235.1040,0.190230,209.0,209.0,0.0
2,TRLH3/33,EU LCS,0,1.0,2,Blue,jng,Cyanide,1924,1,...,12.0,0.0,1.0,0.0,10113.0,191.8815,0.155260,115.0,24.0,91.0
3,TRLH3/33,EU LCS,0,1.0,5,Blue,sup,YellOwStaR,1924,1,...,38.0,2.0,3.0,0.0,9045.0,158.5759,0.128312,11.0,11.0,0.0
4,TRLH3/33,EU LCS,0,1.0,6,Red,top,Darien,1924,0,...,11.0,3.0,1.0,0.0,10050.0,189.9168,0.239525,232.0,213.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
665025,LOLTMNT02_181861,HW,0,5.0,10,Red,sup,XERSUS,1803,1,...,58.0,21.0,18.0,116.0,7686.0,124.1930,0.100351,50.0,50.0,0.0
665026,LOLTMNT02_181861,HW,0,5.0,3,Blue,mid,many,1803,0,...,13.0,6.0,4.0,34.0,10098.0,204.4592,0.209556,228.0,228.0,0.0
665027,LOLTMNT02_181861,HW,0,5.0,8,Red,mid,Phantomles,1803,1,...,8.0,5.0,4.0,23.0,13236.0,308.8852,0.249575,247.0,246.0,1.0
665028,LOLTMNT02_181861,HW,0,5.0,9,Red,bot,raining,1803,1,...,19.0,11.0,8.0,36.0,12650.0,289.3844,0.233819,273.0,267.0,6.0
665029,LOLTMNT02_181861,HW,0,5.0,1,Blue,top,Robocop,1803,0,...,17.0,4.0,6.0,32.0,9146.0,172.7787,0.177088,218.0,214.0,4.0

In [5]:
ranks = pd.read_csv('ranks.csv')
ranks

    playername  rank
0        Faker     1
1       Knight     2
2        Chovy     3
3       Peanut     4
4        Keria     5
..         ...   ...
465    KiWiKiD   466
466      Keane   467
467     Hakuho   468
468   Elementz   469
469       Care   470

[470 rows x 2 columns]

In [7]:
df = df[df['playername'].isin(ranks['playername'])]
df.reset_index(drop=True, inplace=True)
df

,gameid,league,playoffs,game,participantid,side,position,playername,gamelength,result,...,wardsplaced,wardskilled,controlwardsbought,visionscore,totalgold,earned gpm,earnedgoldshare,total cs,minionkills,monsterkills
0,TRLH3/33,EU LCS,0,1.0,3,Blue,mid,xPeke,1924,1,...,12.0,3.0,0.0,0.0,14564.0,330.6861,0.267565,276.0,247.0,29.0
1,TRLH3/33,EU LCS,0,1.0,2,Blue,jng,Cyanide,1924,1,...,12.0,0.0,1.0,0.0,10113.0,191.8815,0.155260,115.0,24.0,91.0
2,TRLH3/33,EU LCS,0,1.0,5,Blue,sup,YellOwStaR,1924,1,...,38.0,2.0,3.0,0.0,9045.0,158.5759,0.128312,11.0,11.0,0.0
3,TRLH3/33,EU LCS,0,1.0,6,Red,top,Darien,1924,0,...,11.0,3.0,1.0,0.0,10050.0,189.9168,0.239525,232.0,213.0,19.0
4,TRLH3/33,EU LCS,0,1.0,4,Blue,bot,Rekkles,1924,1,...,6.0,1.0,0.0,0.0,14210.0,319.6466,0.258633,282.0,250.0,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112289,LOLTMNT03_161676,LAS,0,2.0,10,Red,sup,Cloud,1925,1,...,72.0,19.0,21.0,122.0,8870.0,145.4649,0.111322,44.0,44.0,0.0
112290,LOLTMNT03_162490,LAS,0,2.0,10,Red,sup,Neo,2826,0,...,141.0,43.0,26.0,237.0,11708.0,120.3185,0.098267,59.0,55.0,4.0
112291,LOLTMNT03_162500,LAS,0,1.0,10,Red,sup,Cloud,2928,0,...,122.0,31.0,41.0,220.0,11993.0,117.7049,0.106231,59.0,59.0,0.0
112292,LOLTMNT03_161683,LAS,0,2.0,10,Red,sup,Neo,1868,0,...,108.0,21.0,22.0,175.0,7882.0,121.9272,0.119937,37.0,37.0,0.0
112293,LOLTMNT03_162503,LAS,0,2.0,5,Blue,sup,Cloud,1648,0,...,88.0,23.0,22.0,136.0,7441.0,138.4587,0.128899,47.0,47.0,0.0

In [8]:
df.to_csv('oe_relevant.csv', index=False)