In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('OEFULL.csv')

/var/folders/0h/ch124vqs7dj_96gjw7qq3ksh0000gn/T/ipykernel_77372/2708909022.py:1: DtypeWarning: Columns (3,6,22,23,24,25,26,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('OEFULL.csv')

In [6]:
df

,index,gameid,datacompleteness,url,league,year,split,playoffs,date,game,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
0,862222,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1.0,...,760.0,4854.0,4919.0,-21.0,10.0,23.0,4.0,4.0,6.0,10.0
1,862214,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1.0,...,225.0,621.0,733.0,8.0,1.0,5.0,1.0,1.0,2.0,0.0
2,862212,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1.0,...,206.0,76.0,-512.0,-18.0,3.0,4.0,0.0,1.0,2.0,2.0
3,862213,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1.0,...,140.0,-888.0,351.0,-42.0,0.0,5.0,3.0,2.0,1.0,1.0
4,862216,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1.0,...,28.0,1780.0,2397.0,-19.0,0.0,7.0,0.0,0.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
872023,292715,LOLTMNT02_181861,complete,NaN,HW,2024,NaN,0,2024-11-03 21:08:36,5.0,...,870.0,2295.0,7637.0,-8.0,9.0,23.0,4.0,4.0,9.0,9.0
872024,292706,LOLTMNT02_181861,complete,NaN,HW,2024,NaN,0,2024-11-03 21:08:36,5.0,...,214.0,-716.0,-2609.0,-14.0,1.0,2.0,3.0,1.0,6.0,0.0
872025,292711,LOLTMNT02_181861,complete,NaN,HW,2024,NaN,0,2024-11-03 21:08:36,5.0,...,200.0,716.0,2609.0,14.0,1.0,6.0,0.0,1.0,2.0,3.0
872026,292712,LOLTMNT02_181861,complete,NaN,HW,2024,NaN,0,2024-11-03 21:08:36,5.0,...,264.0,-445.0,1274.0,-28.0,1.0,5.0,0.0,1.0,2.0,0.0
872027,292704,LOLTMNT02_181861,complete,NaN,HW,2024,NaN,0,2024-11-03 21:08:36,5.0,...,202.0,-1536.0,-2066.0,-6.0,0.0,0.0,2.0,2.0,3.0,0.0

In [7]:
df = df.dropna()
axis=1
thresh=int(0.9*len(df))
df = df.dropna(axis=0, thresh=int(0.9*len(df.columns)))

In [8]:
df

Empty DataFrame
Columns: [index, gameid, datacompleteness, url, league, year, split, playoffs, date, game, patch, participantid, side, position, playername, playerid, teamname, teamid, champion, ban1, ban2, ban3, ban4, ban5, pick1, pick2, pick3, pick4, pick5, gamelength, result, kills, deaths, assists, teamkills, teamdeaths, doublekills, triplekills, quadrakills, pentakills, firstblood, firstbloodkill, firstbloodassist, firstbloodvictim, team kpm, ckpm, firstdragon, dragons, opp_dragons, elementaldrakes, opp_elementaldrakes, infernals, mountains, clouds, oceans, chemtechs, hextechs, dragons (type unknown), elders, opp_elders, firstherald, heralds, opp_heralds, void_grubs, opp_void_grubs, firstbaron, barons, opp_barons, firsttower, towers, opp_towers, firstmidtower, firsttothreetowers, turretplates, opp_turretplates, inhibitors, opp_inhibitors, damagetochampions, dpm, damageshare, damagetakenperminute, damagemitigatedperminute, wardsplaced, wpm, wardskilled, wcpm, controlwardsbought, visionscore, vspm, totalgold, earnedgold, earned gpm, earnedgoldshare, goldspent, gspd, gpr, total cs, minionkills, monsterkills, monsterkillsownjungle, ...]
Index: []

[0 rows x 162 columns]